safe: true
markdown: rdiscount
permalink: /:year/:month/:title/
url: http://csukuangfj.github.io
author: csukuangfj
pygments: true
paginate: 24
timezone: "Asia/Shanghai"
github: csukuangfj
pygments: true
myemail: csukuangfj@gmail.com
mydomain: http://csukuangfj.github.io
disqus_shortname: csukuangfj
mygithub: http://github.com/csukuangfj
google-analytics-id: UA-48864598-1
myLinkedIn: http://www.linkedin.com/in/csukuangfj
