markdown: rdiscount
permalink: /:year/:month/:title/
url: http://csukuangfj.github.io
author: csukuangfj
pygments: true
paginate: 24
timezone: "Asia/Shanghai"
github: csukuangfj
pygments: true
myemail: csukfj@csu.edu.cn
mydomain: http://csukuangfj.github.io
